# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "twits", :force => true do |t|
    t.column "text",       :string,   :default => "", :null => false
    t.column "user_id",    :integer,                  :null => false
    t.column "twit_id",    :integer,                  :null => false
    t.column "created_at", :datetime,                 :null => false
    t.column "parent_id",  :integer
  end

  create_table "users", :force => true do |t|
    t.column "user_name", :string,  :default => "",    :null => false
    t.column "user_id",   :integer,                    :null => false
    t.column "location",  :string,  :default => "",    :null => false
    t.column "image_url", :string,  :default => "",    :null => false
    t.column "is_added",  :boolean, :default => false, :null => false
  end

end
